import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Lato } from "next/font/google";
import { AuthProvider } from "@/lib/auth-context";
 // ✅ Add this import

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lato.variable}>
      <body className="font-sans" suppressHydrationWarning>
        <Navbar />
        <AuthProvider>
          
            {children}
          
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
